@WeatherApi_Host_Address=http://localhost:5000

POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "Username": "john",
  "Password": "1234",
}


### GET: Tüm hava durumu tahminlerini getir
GET {{WeatherApi_Host_Address}}/weatherforecast
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiam9obiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzQ4MTE4NDMyLCJpc3MiOiJXZWF0aGVyQXBpIiwiYXVkIjoiV2VhdGhlckFwaUNsaWVudCJ9.Y5bo6VfmXb6RH0bqdV_LFxBXAePNnpqeUjcSuIdLRU8
Accept: application/json

###

### GET: Belirli bir tarihi getir (örnek tarih: 2025-05-21)
GET {{WeatherApi_Host_Address}}/weatherforecast/bydate/2025-05-21
Accept: application/json

###

### POST 1: Güneşli bir gün
POST http://localhost:5000/weatherforecast
Content-Type: application/json

{
  "date": "2025-05-21",
  "temperatureC": 24,
  "summary": "Sunny"
}

###

### POST 2: Yağmurlu bir gün
POST http://localhost:5000/weatherforecast
Content-Type: application/json

{
  "date": "2025-05-22",
  "temperatureC": 16,
  "summary": "Rainy"
}

###

### POST 3: Kısmen bulutlu
POST http://localhost:5000/weatherforecast
Content-Type: application/json

{
  "date": "2025-05-23",
  "temperatureC": 19,
  "summary": "Partly Cloudy"
}

###

### POST 4: Soğuk ve karlı
POST http://localhost:5000/weatherforecast
Content-Type: application/json

{
  "date": "2025-05-24",
  "temperatureC": -2,
  "summary": "Snowy"
}

###

### POST 5: Sıcak ve nemli
POST http://localhost:5000/weatherforecast
Content-Type: application/json

{
  "date": "2025-05-25",
  "temperatureC": 30,
  "summary": "Humid"
}


###

### PUT: Belirli bir tarihi güncelle (aynı tarih olmalı)
PUT {{WeatherApi_Host_Address}}/weatherforecast/bydate/2025-05-21
Content-Type: application/json

{
  "date": "2025-05-21",
  "temperatureC": 28,
  "summary": "Hot"
}

###

### DELETE: Belirli bir tarihi sil
DELETE {{WeatherApi_Host_Address}}/weatherforecast/bydate/2025-05-21

### DELETE: Tum verileri sil
DELETE  {{WeatherApi_Host_Address}}/weatherforecast/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiam9obiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzQ4MTE4NDMyLCJpc3MiOiJXZWF0aGVyQXBpIiwiYXVkIjoiV2VhdGhlckFwaUNsaWVudCJ9.Y5bo6VfmXb6RH0bqdV_LFxBXAePNnpqeUjcSuIdLRU8